#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "autobd"
name = "Autobd"
description.en = "Application permettant de réaliser une bande dessinée, et de l’exporter sous forme d’image"
description.fr = "application permettant de réaliser une bande dessinée, et de l’exporter sous forme d’image"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GNU/GPL"
demo = "https://educajou.forge.apps.education.fr/autobd"
code = "https://forge.apps.education.fr/educajou/autobd"


[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/autobd"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://forge.apps.education.fr/educajou/autobd/-/archive/main/autobd-main.tar.gz"
    sha256 = "a9fd9ead54e251e454786bfbd9f9b24c304b3a89d238bc8bfe37e523f4fa6813"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
